### ISSUE TITLE
Todo Usecase

### ISSUE THREAD

**Issue by zerai** [zerai/x-badge-symfony#1]
- [x] Composer Lock badge
- [ ] Total Download badge
- [ ] Monthly Download badge
- [ ] Daily Download badge
- [ ] Gitattributes badge
- [ ] Dependents badge
- [ ] Suggester badge
- [ ] Stable Version badge
- [ ] Unstable Version badge
